### ISSUE TITLE
Origin of the package

### ISSUE THREAD

**Issue by SylvainCorlay** [conda-forge/libuuid-feedstock#11]
Besides the source tarball from sourceforge.net, I don't see much information about the origin of the package and where it is developed although the last release is from November 2016, so it is fairly recent apparently.

The main advantage of using a conda package over the one from the system is that it may be linked against the same libc as the other packages used with it.

**Comment by SylvainCorlay** [comment]
The zeromq documentation recommends getting `libuuid` from the `e2fsprogs` package. Quoting http://zeromq.org/build:android, one can build it with

```
cd /tmp/
git clone git://git.kernel.org/pub/scm/fs/ext2/e2fsprogs.git
cd e2fsprogs/
./configure --host=arm-linux-androideabi --prefix=$OUTPUT_DIR CFLAGS="-fPIC" 
cd lib/uuid
make
make install
```

**Comment by ocefpaf** [comment]
> Besides the source tarball from sourceforge.net

To be honest I don't recall the origins either. (I do remember I "copied" from an RPM based package somewhere.)

> The zeromq documentation recommends getting libuuid from the e2fsprogs package here 

I would need to perform a few tests but we can probably make that change.
I am in in transit now but I can take a look at this soon. (Please ping me again if I forget. All I need to do is to test it against the other packages that relies on this.)

**Comment by SylvainCorlay** [comment]
I am not even sure that we need to change the origin of the source.

My motivation is for the xeus-cling C++ kernel. Cling has very strict requirements on the used for the compiled code of the interpreter and the one used by the interpreted code, which essentially mean that it must be the same one....
I am doing the exercise of building all the dependencies of cling including llvm, rapidjson etc with gcc-6 from salford system and putting it on a temporary channel. libuuid seems to be the reason why the system's libc is still being loaded...

In any case, when conda-forge has gcc-6 and build its binary packages with it, the world will be a better place !

**Comment by ocefpaf** [comment]
> In any case, when conda-forge has gcc-6 and build its binary packages with it, the world will be a better place !

OK. So, in theory, once we have gcc-6 it may not matter the source of the package, right?

PS: this package is really old and I dropped it as a dependency in most of the package I maintain. I am using `util-linux` from `defaults`.

Closing this as "resolved." Let me know if you have more questions.

**Comment by SylvainCorlay** [comment]
I did not know about `util-linux` from default. I should definitely use that in Xeus. Thanks for the pointer!

**Comment by SylvainCorlay** [comment]
oddly, no recipe for `util-linux` is available on https://github.com/conda/conda-recipes/

So I don't know either were util-linux comes from.

The good thing about it is that it matches the package name of most linux distribution for the same thing.

cc @msarahan
