### ISSUE TITLE
libuuid.so.1: no version information available required by .../lib/libdapserver.so.7

### ISSUE THREAD

**Issue by akrherz** [conda-forge/libuuid-feedstock#15]
This is a copied over issue from conda-forge/gdal-feedstock#200

When I run a tool like`gdalinfo`, I get
```
gdalinfo: /opt/miniconda2/envs/prod/bin/../lib/libuuid.so.1: no version information available (required by /opt/miniconda2/envs/prod/bin/../lib/libdapserver.so.7)
```

This only started after a recent full upgrade of my conda-forge env.
```
$ conda package -w /opt/miniconda2/envs/prod/lib/libuuid.so.1
/opt/miniconda2/envs/prod/lib/libuuid.so.1          defaults::util-linux-2.21-0
/opt/miniconda2/envs/prod/lib/libuuid.so.1          conda-forge::libuuid-1.0.3-1
```
The installation of `libuuid` changes the sym link for `libuuid.so.1` to `libuuid.so.1.0.0`, instead of `libuuid.so.1.3.0` which seems to be the default with a fresh install of conda.  If I manually update that symlink back to `libuuid.so.1.3.0`, the warning message above goes away.

**Comment by akrherz** [comment]
Just to throw some more random thoughts into this, attempting to compile a third party program `mapserver`, I get with either `root` or `prod` envs
```
/usr/lib64/libSM.so.6: undefined reference to `uuid_generate@UUID_1.0'
/opt/miniconda2/lib/libdapserver.so.7: undefined reference to `uuid_unparse@UUID_1.0'
/usr/lib64/libSM.so.6: undefined reference to `uuid_unparse_lower@UUID_1.0'
collect2: error: ld returned 1 exit status
```
the only reason I am getting `libuuid` installed is because of a requirement from `postgresql`, hmmmm

**Comment by ocefpaf** [comment]
Makes sense... I'll try to get to this as soon as possible. (Kind of swamped with the day job this week.)

**Comment by paride** [comment]
This is also happening when launching GMT:
```
$ gmt
gmt: /home/pl/miniconda3/envs/sismo/bin/../lib/./libuuid.so.1: no version information available (required by /home/pl/miniconda3/envs/sismo/bin/../lib/./libdapserver.so.7)
```

**Comment by vvug** [comment]
@ocefpaf Any news about this?

**Comment by wilderfield** [comment]
Does anyone know why the libuuid package in defaults is so crappy, and gives these version problems? I get these warnings if it is linked at runtime, and I get errors if I link it during build time.
