### ISSUE TITLE
conda-forge libuuid and other packages with system libuuid

### ISSUE THREAD

**Issue by ceholden** [conda-forge/libuuid-feedstock#8]
Not quite sure where to ask this because it affects many recipes, but I've run into some issues compiling recipes (QGIS specifically) that use GDAL and Qt because of a linking issue against this `libuuid`. GDAL (through `libdap4`) brings in conda-forge's newer `libuuid` while Qt is built against an older version from the Linux distro, so compiling against the both of them is causing issues. I'm using conda-forge's build of Qt4 by the way but I suspect this happens against default's as well.

Installing and using them side by side doesn't cause issues that I've noticed, but my QGIS build is failing when linking:
``` bash
conda create -n without_forge_uuid -c conda-forge qt
source activate without_forge_uuid
ldd ~/conda/envs/without_forge_uuid/lib/libQtGui.so | grep libuuid
  libuuid.so.1 => /usr/lib/libuuid.so.1 (0x00007f9f49ca4000)
source deactivate
# Check linkage with roping conda-forge `libuuid` in and see it break
conda create -n with_forge_uuid -c conda-forge gdal qt
source activate with_forge_uuid
ldd ~/conda/envs/with_forge_uuid/lib/libQtGui.so | grep libuuid
/home/ceholden/conda/envs/with_forge_uuid/lib/libQtGui.so: /home/ceholden/conda/envs/with_forge_uuid/lib/./libuuid.so.1: no version information available (required by /usr/lib/libSM.so.6)
	libuuid.so.1 => /home/ceholden/conda/envs/with_forge_uuid/lib/./libuuid.so.1 (0x00007f7ef7f0b000)
```

I'm pretty sure this is the issue in my QGIS recipe because everything works when I target a build of GDAL I created without `libdap4`. On a side note, being able to `conda install qgis` is just fantastic.

@ocefpaf do you have any ideas on how to proceed? Seems to me that the solution involves making this `libuuid` another fundamental building block of Qt, similar to how the current Qt recipe includes `libxml2` for compatibility with GDAL ([recipe comment here](https://github.com/conda-forge/qt-feedstock/blob/master/recipe/meta.yaml#L53)). For now I'm using a custom build of GDAL without `libdap4` on my channel but it would be great to have a better solution.

**Comment by ocefpaf** [comment]
> Not quite sure where to ask this because it affects many recipes

Indeed. But here is fine.

I need to check this carefully to avoid a band-aid solution but it sounds like adding `libuuid` is the path to go to ensure it will always be present and linked against the conda-forge version. (Ping @ccordoba12 here for help.)

**Comment by ccordoba12** [comment]
I didn't know that Qt was linked against `libuuid`, but sure we can add it as a dependency. I don't see a problem with that ;-)

@ceholden, could you open a pull request against the Qt feedstock to see how that goes? Thanks ;-)

**Comment by ocefpaf** [comment]
> I didn't know that Qt was linked against `libuuid`, but sure we can add it as a dependency. I don't see a problem with that ;-)

Me neither is sounds like the same issue we had with `icu`. :smile:

**Comment by ceholden** [comment]
Thanks for the feedback! I just submitted a PR adding in the `libuuid` dependency. It pulled in from `conda-forge` and is out to the CircleCI

**Comment by ceholden** [comment]
Conda-forge Qt4 and PyQt4 recipes are now using `libuuid` from this feedstock and this has fixed the issue of trying to combine GDAL and Qt in build recipes.

Closing -- huge thanks to @ccordoba12 !

**Comment by ccordoba12** [comment]
Glad to be of help!! And now it comes Qt5, which will be introduced by Continuum in the next few days ;-)
